Improve postrm/preinst code quality

diff --git a/debian/postrm b/debian/postrm
--- a/debian/postrm
+++ b/debian/postrm
@@ -1,11 +1,15 @@
 #!/bin/sh
+# postinst script for joyent-lxtools
+#
+# see: dh_installdeb(1)
+
 set -e
 
-pkg=joyent-lxtools
+PKG=joyent-lxtools
 
-remove_divert() {
+remove_diversion() {
     if [ ! -z "$(dpkg-divert --list $1)" ]; then
-        dpkg-divert --remove --package $pkg --rename --divert $1.$pkg $1
+        dpkg-divert --remove --package ${PKG} --rename --divert $1.${PKG} $1
     fi
 }
 
@@ -13,8 +17,39 @@ remove_divert() {
 DIVERSIONS="
 "
 
-if [ "$1" = "remove" ]; then
-    for div in $DIVERSIONS; do
-        remove_divert $div
-    done
-fi
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
+case "$1" in
+    purge|remove|abort-install)
+        for DIVERSION in ${DIVERSIONS}; do
+            remove_diversion ${DIVERSION}
+        done
+    ;;
+
+    upgrade|failed-upgrade|abort-upgrade|disappear)
+    ;;
+
+    *)
+        echo "postrm called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
+
